### ISSUE TITLE
Add a LICENSE file?

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/xtrx_julia#15]
Could you please add a LICENSE file?

**Comment by Keno** [comment]
MIT license is fine by us. @enjoy-digital does that work for you also?

**Comment by mithro** [comment]
It would be great to use [the same license as upstream LiteX](https://github.com/enjoy-digital/litex/blob/master/LICENSE).

**Comment by Keno** [comment]
Fine by me also

**Comment by enjoy-digital** [comment]
Added with https://github.com/enjoy-digital/xtrx_julia/commit/96e981b0c5185b084f6d35840832de83f130ea26.
